[build]
base=""
publish="_site"
command="""
set -e
curl -fsSL https://deno.land/x/install/install.sh | sh
/opt/buildhome/.deno/bin/deno task build
"""
[[redirects]]
from="/book/*"
to=":splat"
status=308